# Generated by Django 6.0.4 on 2026-04-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('author', models.CharField(max_length=120)),
                ('date', models.CharField(max_length=50)),
                ('read_time', models.CharField(max_length=50)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('h1', models.CharField(max_length=255)),
                ('alt_text', models.CharField(max_length=255)),
                ('views', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
